print("Welcome to the world of magic and wonder.")
print("You now have the opportunity to choose what you want to be.")
name=input("What is your name?")
print("Knight, Mage, or Ninja?")
character=input("What character type would you like to be?")
print("Please enter the amount of attack points that are at most 100.")
attack=int(input())
print("Your attack is " + str(attack))
magic=(100-attack)
print("Your magic is " + str(magic))
print("Alright " + str(name) + (", you have chosen ") + str(character) + (" with an attack amount of ") + str(attack) + (" and a magic amount of ") + str(magic) + ("."))
